:PROPERTIES:
:GPTEL_MODEL: o1
:GPTEL_BACKEND: ChatGPT
:GPTEL_SYSTEM: You are a large language model and a writing assistant. Respond concisely.\n日本語の学術論文の修正作業を以下に従って協力してください。\n\n- 句読点は「。」「、」を避け、「，」「．」を使用すること\n- 用語の置き換えは控えること\n- 文法を中心に修正を行うこと\n- Emacs Org Mode の記法を前提とすること\n- 長文を短くすること\n\n
:GPTEL_BOUNDS: ((response (3116 3491) (3493 3527) (3530 3564) (3567 3601) (3604 3639) (3642 3682) (3684 3720) (3723 3757) (3760 3790) (4915 4972) (4986 4988) (4999 5013) (5034 5175) (5177 5642) (5644 6265) (6267 6598) (6600 6955) (6980 7074) (7076 7537) (7539 7814) (7816 8199) (8201 8492) (8494 9004) (9006 9439) (9472 9890) (9922 10209) (10211 10461) (10463 11153) (11155 11237) (11239 11425) (11428 11694) (11696 12238) (12245 12534) (12536 12739) (12743 12784) (12788 13216) (13717 13965) (13967 14241) (14727 14963) (14969 15147) (15398 15677) (15679 15976) (15982 16311) (16313 16711) (17322 18061) (18063 18382) (18384 18620) (18622 18831) (18853 18999) (19001 19225) (19227 19754) (19755 20017) (20019 20227) (22494 22720) (22722 22881) (22902 23433) (23435 23648) (23650 23841) (23843 24035) (24225 24473) (24524 24647) (24685 25067) (25069 25521) (25545 25991)))
:END:
#+latex_compiler: platex
#+cite_export: bibtex ipsjsort
#+bibliography: ./references.bib
#+options: timestamp:nil date:nil toc:nil
#+bind: org-latex-default-packages-alist nil
#+bind: org-latex-packages-alist nil
#+bind: org-latex-with-hyperref nil
#+latex_class: ipsj
#+latex_class_options: [submit]
#+latex_header: \usepackage[utf8]{inputenc}
#+latex_header: \usepackage{otf}
#+latex_header: \DeclareUnicodeCharacter{9AD9}{\UTF{9AD9}}
#+latex_header: \DeclareUnicodeCharacter{974F}{\UTF{974F}}
#+latex_header: \usepackage[ipaex]{pxchfon}
#+latex_header: \usepackage[dvipdfmx]{graphicx}
#+latex_header: \usepackage{svg}
#+latex_header: \usepackage{latexsym}
#+latex_header: \usepackage{amssymb,amsthm,amsmath}
#+latex_header: \usepackage{booktabs,siunitx}
#+latex_header: \usepackage{tikz}
#+latex_header: \usepackage[dvipdfmx]{geometry}
#+latex_header: \geometry{right=20mm,left=20mm,top=30mm,bottom=30mm}
#+latex_header: \usepackage[normalem]{ulem}
#+latex_header: \usepackage{url}
#+latex_header: \DeclareUrlCommand\doi{\urlstyle{tt}}
#+latex_header: \usepackage{cleveref}
#+latex_header: \crefname{equation}{式}{式}
#+latex_header: \crefname{figure}{図}{図}
#+latex_header: \crefname{table}{表}{表}
#+latex_header: \crefname{section}{第}{第}
#+latex_header: \creflabelformat{section}{#2#1節#3}
#+latex_header: \crefname{subsection}{第}{第}
#+latex_header: \creflabelformat{subsection}{#2#1小節#3}
#+latex_header: \let\oldref\ref
#+latex_header: \renewcommand{\ref}{\cref}
#+latex_header: \makeatletter
#+latex_header: \def\：{：}
#+latex_header: \makeatother
#+begin_src emacs-lisp :eval nil :exports none
  (with-eval-after-load 'ox-latex
    (add-to-list 'org-latex-classes
                 '("ipsj"
                   "\\documentclass{ipsj}"
                   ("\\section{%s}" . "\\section*{%s}")
                   ("\\subsection{%s}" . "\\subsection*{%s}")
                   ("\\subsubsection{%s}" . "\\subsubsection*{%s}"))))
#+end_src

#+RESULTS:

#+begin_export latex
\title{語彙プロファイルに見られる八代集の語彙変化}

\etitle{Profile-based lexical change in the Hachidaishu}

\author{陳 旭東（東京科学大学 環境・社会理工学院）}{Xudong Chen (School of Environment and Society, Institute of Science Tokyo)}{}
\author{ホドシチェク ボル（大阪大学 大学院人文学研究科）}{Bor Hodo\v{s}\v{c}ek (Graduate School of Humanities, Osaka University)}{}
\author{山元 啓史（東京科学大学 環境・社会理工学院）}{Hirofumi Yamamoto (School of Environment and Society, Institute of Science Tokyo)}{}

\begin{abstract}
  本稿では，八代集の語彙変化について，言語の内容を見る視座と言語の様式
  を見る視座を調整するための計算手法を論じた．方法としては，同義類義の
  語群，同上位概念の語群，関係なしの語群の3水準で小さいサンプルを用意
  し，2歌集間のサンプル内の語彙変化量を語形分布の非類似度で計算した．こ
  の変化量に基づき，八代集の (1) 変化最大の隣接2歌集，(2) 時代区分，3)
  推移のパターンを検討した．結果として，3水準の分析結果が共通し，調整の
  有効性はさらなる検証を要する．一方，分析結果は文学史においても合理的
  に説明しうる内容となった．
\end{abstract}

\begin{jkeyword}
  八代集，語彙分析，和歌，言語変化
\end{jkeyword}

\begin{eabstract}
  This paper discusses quantatative methods for adjusting the
  perspectives of examining thematic contents and lexical choices in
  relation to language change in the Hachidaishū. As a method, small
  samples were prepared at three levels: groups of synonymous and
  near-synonymous words, groups of words sharing the same
  superordinate concept, and groups of unrelated words. The amount of
  lexical change within samples between two anthologies was calculated
  using the within-sample dissimilarity of word choice
  distributions. Based on this amount of change, we examined (1) the
  adjacent pair of anthologies with the maximum change, (2)
  periodization, and (3) patterns of transition in the Hachidaishū. As
  a result, the analytical results at the three levels were
  consistent, though the effectiveness of the adjustment requires
  further verification. On the other hand, the analytical results
  proved to be rationally explained within literary history.
\end{eabstract}

\begin{ekeyword}
the Hachidaishu, waka, lexical analysis, language change
\end{ekeyword}

\maketitle
#+end_export
 
* はじめに<<sec:intro>>
本研究の目的は，古典日本語の語彙分析において，全語彙によるマクロレベル
の調査に代わり，関連語群の部分語彙サンプルを用いた調査手法を八代集（古
今・後撰・拾遺・後拾遺・金葉・詞花・千載・新古今）の語彙変化に適用する
ことである．この方法に関して関連研究と関連理論を整理し，語彙変化の研究
が蓄積している八代集のテキストデータを分析する．

複数の言語変種間の語彙変異・変化は，それぞれの変種の全語彙の差集合で検
討することの古典語における有効性が指摘されている
[cite/cf:@kondo2011Heian; @tsukishima1992Kunten]．一方，語彙の変化・変
異の比較手法には，以下の3点の拡張が可能であると考える．第一に，語の推
敲など様式の側面と，テーマ・トピックなど内容の側面が混在し，両者を分離
して調べられていない．第二に，「変種 \(A\) の話者はみな \(X\) を言い変
種 \(B\) ではまったく言わない」といった表現 \(X\) よりも，「変種 \(A\)
の話者は \(Y\) を多用し変種 \(B\) はあまり使わない」といった数量的差異
のある表現 \(Y\) が一般的だ [cite/cf:@Wolfram2004Social] が，集合差で
はこうした \(Y\)が拾えない．第三に，集合差分では語の消滅・出現のみ把握
できるものの，その消長を用いた語彙差（語彙変化）の数量化は十分に検討さ
れていない．そこで，2点の調整を考える．第一に，語彙差の調査では形式と
内容のいずれかを統制し，片方を分析する方法を開発する．第二に，集合の差
による分析に代わり，語彙における語の確率分布の差を利用し，語彙変化を測
定する方法を検討する．

第一の調整については，日本語学で既に実践例がある．文献 [cite/t/c:
@miyazima1979Kyosanto; @hasumi1991Ichi] は，同一作品の複数バージョンに
注目して，語彙・語の変化を検討した．文献 [cite/t/c:@kitasaki2024Heike;
@tanaka2014Konjaku] は，パラレルテキストで語の対応づけを行い，内容の差
を捨象したうえで対応づけをもつ言語要素の間の言語変化を調べた[fn::
[cite:@kitasaki2024Heike] は語彙に着目していない．]．これらの研究は，
内容の統制としてパラレルコーパス相当の資料を利用しているが，パラレルコー
パスは語彙史の資料としてごく限られ，特定資料への依存を避ける方法論も求
められる．たとえば，本稿の和歌資料では異本こそあるが，同一作品の異なる
変種は存在しない．また，既存研究の多くは特定変種の特徴的な表現や語彙交
替を事例として記述するにとどまり，交替しうる語の選好を数量化する，すな
わち第二の調整の趣旨は十分に扱われていない．

このように，この第二の調整は古典語の語彙論の応用可能な領域の文体・位相
の研究におよぶが，日本語の研究では語彙論での実践が少ない[fn::語彙を用
いた歌語の変化については，語彙そのものではなく，各種の品詞分布，修飾語
対動詞比率など，語彙から計算された二次的なマクロ指標を用いる傾向がある
[cite/cf:@nishihata1992Waka; @hatano1941Waka]．]．対して，計量方言学は，
交替しうる表現の分布を用いて変種間の違いを定量的に測定し言語変種の分類
に貢献する方法論が充実している．そこで，それらを参考としつつ，勅撰和歌
集の代表である八代集における変遷について，語彙を用いた計量分析を検討す
る．

本稿が扱う八代集は，成立年がおおむね300年の範囲で均一なため，平安期の
貴族社会が好んだ言語の変遷を見る手がかりとなる．表現論と語彙論では，そ
の変遷が多く議論されてきたが，「形式・内容」を切り離して語彙変化を検討
する方法論はまだ確立されていない．そこで本稿では，方法論的に形式的変化
と内容的変化の 2 視座を調整する手法として，語彙変種計量論 (lexical
lectometry) [cite/cf:@Speelman2003Profilebased] に基づく拡張
（[[sec:ext-sem-ctrl]]後述）を提案する．八代集を広義に時期別の「変種」とみ
なし，その変化量を測定して従来の研究の知見と照合する．さらに，視座の調
整による結果の変化の有無と，変化があった場合の規則性も検討する．

* 先行研究<<sec:prev-work>>
本稿ではまず八代集の言語変化と転換点を説明し，方法論の前提として，形式
的変化と内容的変化の視座調整の理論的背景と日本語語彙論の研究手法に基づ
く拡張可能性を先行研究に照らして整理する．

** 八代集の言語変化<<sec:poem-lang-change>>
八代集は，『古今和歌集』（905年頃）から『新古今和歌集』（1205年）まで
を含む8つの勅撰和歌集であり，同一の題材かつ成立年が比較的等間隔なため，
時期ごとのスナップとして和歌語彙の通時的分析に適した資料である．和歌の
言語研究では，語形の選好の交替とテーマの流行が混在し，両者の境界が曖昧
である．文芸研究としては，和歌の詠まれる情景 [cite:@ueno1976Koshui]，
流行 [cite/cf:@kawamura1991Sekkan]，歌語辞典としては「桜」「梅」など歌
語間の共出現 [cite/cf:@katagiri1983Uta] が指摘されている．八代集の表現
の転換点としては，『拾遺和歌集』（拾遺）から『後拾遺和歌集』（後拾遺）
への移行が，「褻」（私的・日常的）から「晴」（儀礼的・公式的）への転換
として言及されている[cite/cf:@ueno1976Koshui; @kawamura1991Sekkan]．

一方，前述脚注でも言及したとおり，語彙を視座に歌語の変化を調査した研究
では，語彙そのものではなく，語彙の各種品詞の比率や修飾語対動詞比率など
の語彙指標を利用する傾向がみられる[cite/cf: @tsuji1998Uta;
@nishihata1992Waka; @hatano1941Waka]．本稿の趣旨である，語の言い換えな
どの特定の語群内の選好を視座とした数量化は確認されていない．また，計算
文学研究として，文芸研究での八代集の転換点と，言語学（語彙論）としての
八代集の転換点を包括的に計算する架橋となる方法論的枠組みが期待される．

** 語彙変化分析における意味論的統制<<sec:sem-ctrl>>
前述の語彙論における「内容の統制」について述べる．日本語の語彙の研究で
は，コーパスの内容面の干渉を捨象しようとする考えは文献 [cite/c/t:
@miyazima1979Kyosanto]ですでに実践されている．一方，後述する「語彙的変
種計量論 (lexical lectometry)」の枠組み [cite/cf:
@Speelman2003Profilebased; @DePascale2019Tokenbased;
@Geeraerts2023Lexical] では，「意味論的統制(semantic control)」として
理論と方法を体系的に整理している．その系統を踏まえ，日本語語史・語彙史
の分析視座を改めて概観する．

*** 意味変化と命名変化の区分の明確化<<sec:ono-sem-var>>
言語変異の研究対象について，onomasiological variation と
semasiological variation の二分が[cite/t/c: @Geeraerts1994Structure]で
提唱されている．onomasiological variation は同じ意味を表す表現の変異
（命名の変化）であり，semasiological variation は同じ表現の指す意味の
変異（意味の変化）である[cite/cf: @Geeraerts1994Structure]．

前者「意味の変化」には，語史研究による精緻な分析，計量的手法の開発と応
用など，多様な分析が展開されている[cite/cf: @aida2023Kotonaru;
@takahashi2025Tango]．後者「命名の変化」には，同語の異表記の選好変化と
して論じられる場合が多い [cite/cf:@mabuchi2016Kindai;
@takahashi2016Kindai; @takahashi2019Kindai]．後述にとりあげる．また，
類義語同士の交替でも，最終的には意味分担の相違と使い分けに焦点が置かれ
る[fn::語彙でなく構文・統語変異の場合，方言研究や社会言語学変異理論を
視野に入れた特定表現群の交替分析が [cite/cf:@yamada2021Edo;
@matsuda2019Okazaki] など比較的多い．]．このように，命名変化には常に意
味変化の要素が絡むと考えられる．

一方で，日本語の語彙の集合・体系としての変化では，(1) 語彙の集合全体・
部分集合の各要素の消滅・出現と(2) その集合がもつ数量的特徴[fn:: 各種品
詞の比例，語種率，タイプ/トークン率など．]の2点が主な分析対象となりや
すい．この場合，語史のように命名変化・意味変化を区別する必要はない．文
体や時期，ジェンダなどによる語彙差を論じる際も，数量的指標を利用するこ
とが多い（[cite/cf:@kondo2018Kindai]など）．他方，方言地理学では同義の
語形分布を用いる計量方言学の研究があり，同概念異語形の分布で方言間の距
離を計算する方法が多用されている．これらの手法にならい，語史・語彙史で
検討した使い分けうる類語群・関連語群を用いて語彙の違いを測る手法が語彙
史でも考えられる．その考えは，八代集の各時期にみられる語彙表現の差を分
析するうえで示唆となる．

*** 語彙的変種計量論<<sec:lectometry>>
計量方言学の手法をより一般化した方法論として「変種計量論 (lectometry)」
の枠組みが提案されている．時期ごとの言語変化は地域方言とは異なり，狭義
の言語「変種」や日本語学でいう「位相」としては扱えないが，変種計量論で
はそのような時期差も「変種」の1つとして考慮される
[cite/cf:@Geeraerts2023Lexical]．

「変種計量論」は，複数の言語変数[fn::言語変数は，同一の内容を意味する
表現群を指す[cite/cf:@Labov1972Sociolinguistic]．]を収集し，それらを定
量的に分析して言語変種間の距離を測定する方法論群である[cite/cf:
@Ruette2014Semantic]．言語表現の要素の1つである語彙を用いた「語彙的変
種計量論(lexical lectometry)」はその下位区分に位置し，本稿では主にこの
語彙的変種計量論の枠組みを採用する．

語彙的変種計量論では，意味論的統制として語彙変数（言い換えうる語形の群）
を利用している．1つの語彙変数に属す言い換えの2変種間の使用度数・率の差
で2変種の変化量を計算し，内容による変化量を変化量全体から取り除く
（[[sec:prof-dissim]]にて後述）．こうして得られた変化量を複数の語彙変数で
統合すれば，2変種の全体的な語彙差が算出できる．この測定手法は，日本語
の語彙論・語彙史ではまだ実践されていない．

*** 2種類の語彙変数の認定アプローチ
上記「語彙変数」，または言い換えうる語形の群の認定は完全に客観にはなり
えない．本来，変異理論の「変数」概念では，変数内の語形はあらゆる条件で
互換でき，命題として真値が同値である必要がある．しかし，語彙レベルでそ
の厳格な同義判定を行うのは難しく[cite/cf:@Lavandera1978Where]，結果と
して語彙変異は音韻などに比べ，変異理論の分析の周縁に置かれがちであった
[cite/cf:@DePascale2019Tokenbased]．

変種計量論では，このような語形たちの真理条件レベルでの同値を「形式的同
値 (formal equivalence)」とし，それよりルーズな同値である「概念的同値
(conceptual equivalence)」を提起している
[cite/cf:@Geeraerts2023Lexical; @DePascale2019Tokenbased]．概念的同値
とは，同一のデノテーションを異なる概念として語彙化した2語の間の同義の
ことである．たとえば，同じズボンについて， /breeches/ とでも /pants/ とで
も言えるため，形式的同値ではない2語は，概念的同値にあたりうる
[cite/cf:@DePascale2019Tokenbased;@Geeraerts2023Lexical][fn::踵の上ま
での長ズボンか，膝を覆う程度の半ズボンか明確にできない場面が現実には多
く存在する．]．

その結果，[ /trouser/ = /pants/ ] のような形式的同値の語彙変数のみならず，
半ズボンとして [ /breeches/ = /trouser/ = /pants/ ] のような概念的同値の語形
たちも語彙変数であると捉えられる．さらに，概念的同値にある変異形の選好
は，異なる変種の話者が行う言語化，とくに認知面の概念のカテゴリ化の根拠
として成立するとされる[cite/cf:@DePascale2019Tokenbased]．

本稿の文脈では，こうした 2 種類の同値による語彙変数の規定は，意味統制
として 2 段階での調整を可能にし，異なる観点で語彙差を観測可能にしたと
考える．

** 語彙変化の統制の拡張の可能性<<sec:ext-sem-ctrl>>
上述した語彙変化・変異の統制は語彙変種計量論の枠組みに基づくが，他方で
日本語の語彙論的研究を踏まえれば，前掲の2段階に加えて統制の水準をさら
に拡張しうる可能性がある．具体的には，全体的な語彙変化を対象とする代わ
りに，部分語彙を取り出して詳しく検討する手法がすでに事例として報告され
ている[fn::意味の軸を超える他のカテゴリによる部分語彙を用いた手法
[cite/cf:@ito2008Goi] なども参考となるが，本稿では意味の軸に関連する
もののみとりあげる．]．

*** 上位概念での語群比較：意味分野別構造分析法
意味分野別構造分析法 [cite/cf:@tajima2000Goikenkyu] は，語彙の意味分野
を単位に部分語彙を区分し，その比較を行う手法である．たとえば，親族呼称
や色彩表現などの意味分野ごとに2変種を比べ，片方にのみ含まれる語を意味
分野レベルで特定できる．意味分野（上位概念）は語彙変数に当たらないが，
意味の近さを粗く統制する点で類似すると考えられる．一方，2変種の語を直
接比較する代わりに意味分野で整理すれば，一定の統制をかけつつ詳細な差を
捉えやすくなる．

*** 同語異表記群の比較：表記の変遷研究
日本語では，同語であっても異なる表記が用いられる．研究
[cite/t/c:@takahashi2019Kindai] は「カワル・カエル」などを例に表記の変
遷を示し，研究 [cite/t/c:@takahashi2016Kindai] は「ハレル」「オビル」
などの複数表記の合一の傾向を指摘した．研究
[cite/t/c:@mabuchi2016Kindai] は，近代の二字漢語で多様な表記が衰退し統
一へ向かう要因を論じた．また，研究 [cite/t/c: @takahashi2016Kindai;
@takahashi2019Kindai] は表記と意味の結び付きに基づくより精緻な分析を提
示している．同語異表記で括った語形の比較は，意味統制の観点からは語彙変
数を最も厳格に設定したと認識できる[fn:: ただし，同語であっても，表記ご
とに表意機能が異なり，使用者に別語意識をもつ場合もある．その使い分けは，
研究 [cite/t/c:@takahashi2025Tango] などでも議論されている．同一の語形
の多義性は，今後の課題とする．]．

*** まとめ：意味統制の水準の多段階化  
語彙変化の特定側面を見るための統制は，ここまでに形式的同値から概念的同
値の2段階を取り上げたが，日本語語彙研究では，同語異表記と意味分野の調
査手法を参考に，以下のように多段階化できる[fn::この拡張はあくまでも変
種計量論の枠組みを日本語語彙研究に適用する試みであり，その枠組みの本来
もつ認知社会言語学的意図とは必ずしも合致しない点に留意されたい．]：

統制なし → 意味分野統制 → 概念的同値語群統制 → 形式的同値語群統制 → 同
語異表記群統制 → 同義トークン異表記統制

本稿では，データの制約上「ランダム語群 → 同概念語群 → 類義同義語群」に
簡略化し，この軸に沿って八代集各時期の語彙を部分語彙に分け，サンプルの
分布差を用いた計算で分析する．こうすることで，用語の選択の変化をテーマ
の選択から段階的に濾過できると想定される．最終的に，方法論的見解として，
八代集の語彙変化の見え方がこの統制水準によって異なるか，異なる場合その
違いが連続的か離散的かを明らかにする．

* 方法<<sec:methods>>
** 材料<<sec:materials>>
*** 八代集語彙データセット<<sec:hachidaidb>>
本研究では八代集語彙データセット [cite/cf:@Hodoscek2022Developmenta]
を使用した．このデータセットは，新編国歌大観 CD-ROM 版の二十一代集デー
タ[cite/cf:@shinhen1996CDROM] を基に，新日本古典文学大系本二十一代集の
書籍を参照して正規化と単位分割を行った．作者と歌番号は資料
[cite/t/c:@nakamura1999Kokubungaku] 所収の作者タグを利用し，各単語には
国立国語研究所の分類語彙表 [cite/cf:@nakano1994Bunruigoihyo] に準じた
分類番号を付与した．八代集の分類語彙表の詳細は次節で述べる．

# #+attr_latex: :placement [b]
# #+caption: 八代集の詳細
# #+name: tbl:hachidaidb-stats
# | No. | 歌集名 | 略称   | 成立時期 | 和歌数 |
# |-----+----------+--------+----------+--------|
# |   1 | 古今集   | 古今   | ca. 905  |   1100 |
# |   2 | 後撰集   | 後撰   | ca. 951  |   1425 |
# |   3 | 拾遺集   | 拾遺   | ca. 1007 |   1351 |
# |   4 | 後拾遺集 | 後拾遺 | 1086     |   1218 |
# |   5 | 金葉集   | 金葉   | ca. 1121 |    665 |
# |   6 | 詞花集   | 詞花   | ca. 1151 |    415 |
# |   7 | 千載集   | 千載   | 1188     |   1288 |
# |   8 | 新古今集 | 新古今 | 1205     |   1978 |

** 分類語彙表<<sec:wlsp>>
八代集データセットにおける八代集用の語彙分類番号の階層を用いることで，
「ランダム語群」「同概念語群」「類義同義語群」の語群をサンプリングする．

分類語彙表番号は，国立国語研究所によって編纂された日本語の大規模なシソー
ラスであり，階層的な意味カテゴリを伴うエントリが収録されている
[cite/cf:@Asahara2022CHJWLSP]．本稿で用いる分類は，現行の分類語彙表番
号の旧版[cite/cf:@nakano1994Bunruigoihyo] に準じており，和歌に特有で現
代語には存在しないカテゴリを追加し，同語の異表記を細かく分類する拡張も
行った．分類番号は，たとえば，語彙項目「昨年」の分類番号が =1.1642= であ
る．先頭の =1= は体言を意味し，その下位に =1.1= （部門：関係）， =1.16= （中
項目：時間）， =1.1642= （分類項目：過去）が意味の階層によって分類されて
いる．

# 分類語彙表番号は当初，現代語への付与のみが行われていたが，後に古典語
# への付与も進められた [cite/cf:@Asahara2022CHJWLSP;
# @miyazima2014Nippon]．

# #+caption: 分類語彙表番号の例（[cite/cf:@Asahara2022CHJWLSP] に基づく）．「昨年」の番号は =1.1642= である．先頭の =1= は体言を意味し，その下位に =1.1= （関係）， =1.16= （時間），  =1.1642= （過去）が階層的に分類されている．このように，番号は階層構造を反映しており，語彙の意味的・統語的な位置づけを示している．
# #+attr_latex: scale=\textwidth 
# #+name: fig:wlsp
# #+begin_figure
# #+begin_example
#     　　1.1642  昨年
#     　　├─────────────────────
#     　　└─ 1                    体　：類
#     　　    └─ 1.1              関係：部門
#     　　        └─ 1.16         時間：中項目
#     　　            └─ 1.1642   過去：分類項目
# #+end_example
# #+end_figure

** 手続き<<sec:procedure>>
語彙変化を測定するには，語彙的変種計量論の初期手法であるプロファイル基
盤分析 [cite/cf: @Speelman2003Profilebased] が提示するプロファイルの非
類似度を用い，各歌集の語彙的選好の差を数値化する．さらにクラスタリング
分析と統計モデリングにより，通時的変遷の転換点（差の最も大きい隣接歌集）
を調べる．本稿でのプロファイルの概念の拡張，その非類似度の計算，そして
サンプリング手法を述べる．

*** プロファイルと変化量の計算<<sec:prof-dissim>>  
プロファイル基盤分析における「プロファイル」とは，語彙変数の下位語形と
変種とのクロス表で，各変種における同義・類義語形の使用頻度・率を示す
（[[tbl:profile-ex]]）．本稿では，語彙変数をさらに一般化し，3水準の意味の
類似度をもつ語群を用いてプロファイルを作成する．

#+attr_latex: :placement [t] 
#+caption:  プロファイルの例：「葎」のプロファイル；数字は各時期の使用率を意味する．
#+name: tbl:profile-ex
|            | 後拾遺以前 | 後拾遺以降 |
|------------+------------+------------|
| ムグラ     |       100% |      62.5% |
| ヤヘムグラ |         0% |      37.5% |

プロファイル非類似度は，その語群に限定した変種間の変化量を示す値である．
計算手法は文献 [cite/t/c: @Speelman2003Profilebased]に準拠し，変種をベ
クトル，語形の相対頻度を各変種ベクトルの次元として扱い，2者の1ノルムの
距離を求める．たとえば，「ムグラ・ヤヘムグラ」プロファイルでは，後拾遺
以前（1.00,0.00）と後拾遺以降（0.625,0.375）の距離は \(|1.00 -
0.625|+|0.00-0.375|=0.75\)となる．さらに，変化量の有意性は絶対頻度での
対数尤度検定で判定し，有意でない場合変化量を0と見做す．

2変種の全般の語彙差は複数のプロファイル非類似度を統合して計算される．
複数の類似度を統合する方法としては，平均，もしくは，重みづけ平均があげ
られる[fn:: 重みづけの方法については研究 [cite/t/c:
@Ruette2014Semantic] がプロファイルの重要度，内的整合性などに基づく計
算方法を詳しくとりあげている．]．本稿では単純平均を用いる．すなわち，
\(n\) 個のプロファイルで計算されたプロファイル非類似度 \(d_1, d_2,
\ldots, d_n\) を用い，全体の語彙差を\(D=\frac{1}{n} \sum_{i=1}^{n}
d_i\) とする．

*** 3 水準の語群のサンプリング<<sec:sampling>>
#+attr_latex: :float table* :placement [t]
#+caption: 3水準の語形集合のサンプル例
#+name: tbl:control-level
| 水準           | 説明                                  | サンプリング基準             | 例               | サンプル数 |
|----------------+---------------------------------------+------------------------------+------------------+------------|
| ランダム群     | 意味的統制なし                        | 分類番号分類項目不一致       | {花橘, 雁}       |        196 |
| 同上位概念群   | 広義の意味分野共有（例：「植物」語彙） | 分類番号分類項目一致         | {花橘, 稲, 桜花} |        928 |
| 類義・同義語群 | 狭義の概念共有（例：「植物-葎」語彙）  | 分類番号同語判定＋目視選別 | {葎, 八重葎}     |         43 |

前述のように，本稿では意味統制の水準を3段階に拡張した．これら3水準に対
応する語群を用いてプロファイルのサンプルを生成し，変化量を計算する．

サンプルリングは，[[sec:wlsp]] で説明した分類語彙表番号を基に実施する
（[[tbl:control-level]]）[fn::分類番号づけの自動化，分類番号に依存しない水
準分けは今後の課題にしたい．]．研究
[cite/t/c:@Speelman2003Profilebased] では，概念的同値に基づく語群は2～
3個の語形からなる例が多い．また，八代集の語彙中で類義・同義語群のサイ
ズも基本的に2～5個に収まる．これらに合わせ，ランダム水準と同概念水準の
語群のサンプルも2～5個の語形を含めるように設定した．ランダム水準の語群
は，対象となる30の意味分野[fn:: 各和歌集において異なり語数が2以上存在
し，かつ語群全体で延べ語数が1以上になるように選んだ．この基準は，デー
タセットを8つの時代のサブセットに分けて8つの時代の変化を調べる際に，時
代ごとの異なり語数が1か0かになるような意味分野を避けるために考えた．]
の全語彙から，サイズが2～5の非同概念の語形の群をそれぞれのサイズで50回
ずつ無作為抽出（非復元抽出）し，合計で200イテレーションを実施した．同
概念語群は，対象の30の意味分野ごとにサイズ2～5個の同概念の語形の群をそ
れぞれのサイズで30回ずつ無作為抽出（非復元抽出）した．同義類義語群は分
類番号を参考に目視で全数抽出した．最終的にランダム群196サンプル，同概
念語群928サンプル，同義類義語群43サンプルを得て，これらを変化量の計算
と分析に用いる．

*** 変化量の分析<<sec:analytics>>
**** 統計モデリング：変化量最大の隣接2歌集<<sec:stat-anal>>
それぞれの意味統制の水準で変化量が最大となる隣接2歌集の有無と相違を調
べるために，語群サンプルの変化量（プロファイル非類似度）をハードル対数
正規回帰モデル[fn:: 語群サンプルのプロファイル非類似度の分布は対数正規
分布に従うと観測されているが，対数正規分布に含みえない0値データも含ま
れている．このような分布にはハードル対数正規分布を適用する
[cite/cf:@Chaudhry2018NGO]．統計分析にあたり，R 言語（4.2.1;
[cite:@RCoreTeam2022Language]）， =brms= （2.20.4），
stan(cmdstanr)（2.36.0）と =cmdstanr= （0.8.1）を用い，モデルについては，
事前分布をデフォルトのままとし，MCMC (Hamiltonian Monte Carlo) を用い
た．4本のチェーンと各チェーン4000ステップ（うち1000ステップはウォーム
アップ）でサンプリングを行っている．\(\hat{R}\) はすべて1.00程度で，事
後分布の有効標本サイズのBulk部とTail部も十分な値を示した．] で分析する．
モデルでは，固定効果として隣接する勅撰集の組 (=phase=)[fn:: たとえば，
「古今→後撰」「拾遺→後拾遺」「千載→新古今」など，7つの組がある．] と意
味統制の水準，さらに二者の交互作用（ =phase= \(\times\) 統制水準）を含め
る．サンプルとなる語群のサイズも統制変数として，固定効果に組み込む．ラ
ンダム効果項（ランダム切片）として語群の属する意味分野 (=profile=) と語
群のサンプル ID を設定する．最終的に，各統制水準ごとに =phase= のレベル
間のコントラスト（隣接ペア間の差）を事後分布からサンプリングし，変化が
特に大きい =phase= の有無と3水準での違いを検討する．

**** クラスタ分析：八代集語彙の分類<<sec:clus-anal>>
上記統計モデリングはサンプルごとの変化量を用いた．次に研究
[cite/t/c:@Speelman2003Profilebased] を踏襲し，サンプルの非類似度の平
均を求めて大局的な語彙変化量を算出し分析する．八代集の語彙の分断を分類
問題と見做し，クラスタ数を3と仮定し，非類似度行列を基にk-means法でクラ
スタリングを行う．最後に，3水準で見る八代集の語彙の分類の相違を確認す
る．

**** 多次元尺度構成法：語彙の揺れのパターンの可視化<<sec:mds-anal>>
最後に，上記の大局的な語彙変化量の行列を基に多次元尺度構成法
[cite/cf:@Kruskal1964Multidimensional] を実施し，第1主軸に八つの勅撰集
の語彙の相対的位置づけを\(x\)軸に，成立年順に\(y\)軸へ等間隔に配置して，
可視化する．さらに，上記2つの分析と同様に，3水準での相違を検討する．

* 結果<<sec:results>>
** 変化量最大の隣接 2 歌集<<sec:stat-res>>
隣接 2 歌集は統計モデルでは =phase= と呼び，八代集には計 7 つの =phase= が
ある．各統制水準を通じ，それらの =phase= のうち他のすべての =phase= より変
化量が大きい例は存在しなかった．

具体的に，各統制水準での =phase= の変化量の差は [[fig:phase-diff]] で確認で
きる．同図では，ランダム・同概念・同義類義の3水準における =phase= の変化
量の比較のうち，95% の信用区間(CrI)で有意に 0 とならない比較のみを提示
している．すべての =phase= のレベル間コントラクト（計 21 対）のうち，ラ
ンダム水準は 5 対，同概念水準は 14 対，同義類義水準は 4 対に差が確認さ
れた．

それぞれの水準で共通した変化量の差としては，「拾遺→後拾遺」より「古今→
後撰」が小さい（ランダム水準：Median=0.003，95% CrI [0, 0.06]；同概念
水準：Median=0.002，95% CrI [0.01, 0.03]；同義類義水準：Median=0.006，
95% CrI [0, 0.13]）ことと，「金葉→詞花」より「古今→後撰」が小さい（ラ
ンダム水準：Median=0.003，95% CrI [0, 0.06]；同概念水準：Median=0.004，
95% CrI [0.02, 0.05]；同義類義水準：Median=0.008，95% CrI [0.01, 0.17]）
こと，2点あった． =phase= 間の変化量の差はすべて 0.1 未満だった．それ以
外では[[tbl:model-estimates]] において「詞花→千載」に正の効果が確認された
（Median=0.212，95% CrI [0.07, 0.35]）[fn::モデルでは「古今→後撰」を比
較の基準として効果を変換していないestimatesであることに留意されたい．]．
また，サンプルの語群サイズには変化量への正の効果が見られた
（[[tbl:model-estimates]]）．

** 八代集の分類<<sec:clus-res>>
非類似度の平均をもとに計算した２つずつの和歌集のグローバルな語彙差の行
列でクラスタリングした結果を示す（[[fig:path]]）．

ランダム水準では，「古今・後撰・拾遺」「後拾遺・金葉・詞花・千載」「新
古今」の３クラスタに分類された．同義類義水準は，ランダム水準と同様な分
類であった．

中間水準である同概念水準では，「古今・後撰・拾遺」「後拾遺・詞花・千載・
新古今」「金葉」の３クラスタに分類された．他の２水準とは，「金葉」「新
古今」の扱いに相違があった．

** 語彙の揺れのパターンの可視化<<sec:mds-res>>
多次元尺度構成法で語彙差の行列を可視化し，第1主成分軸を \(x\) 軸，成立
年順を \(y\) 軸に配置した（[[fig:path]]）．その結果，3 水準で類似した傾向
がみられ，「古今→後撰→拾遺→後拾遺→金葉」は負から正へ移行し，「拾遺→後
拾遺」で0値を切り，「金葉→詞花→千載→新古今」は負方向と正方向を往復する
パターンを示した．

#+attr_latex: scale=\textwidth
#+attr_latex: :placement [t]
#+caption: 異なる統制の水準に基づく =phase= 変化量のコンストラクト．それぞれの有意差の事後分布の中央値と95%の信用区間 (CrI) を \(\Delta =\)  =[<Median>, 95% CrI [<lower.CrI>, <upper.CrI>]= で提示した．差が 0 より大きい確率は \(P(\Delta > 0) =\) =<possibility>= で提示した．
#+name: fig:phase-diff
[[./figs/fig-diff-phase-1.svg]]

#+attr_latex: scale=\textwidth
#+attr_latex: :placement [t]
#+caption: 多次元尺度構成法とクラスタリングによる第1主成分の可視化．矢印は成立年順を示す．色はクラスタを示す．クラスタリングにより三代集である古今・後撰・拾遺，および詞花・千載が安定のクラスタを形成する一方，金葉と新古今の位置は水準により変動する．\(x\) 軸での変動パターンは，「古今→後撰→拾遺→後拾遺→金葉」は負から正値へと移行し，「拾遺→後拾遺」で0値を切る．「金葉→詞花→千載→新古今」は，負方向と正方向の方向転換の繰り返しを示す．
#+name: fig:path
[[./figs/aggregate-path.svg]]

#+attr_latex: :placement [t]
#+caption: モデル推定値．太字は95%信頼区間が0を含まない係数．
#+name: tbl:model-estimates
| 係数                                      | 推定値 | 95% CrI          |
|-------------------------------------------+--------+------------------|
| $\alpha_{\mu}$                            | -2.472 | [-2.596, -2.342] |
| $\alpha_{\text{hu}}$                      | -5.043 | [-5.843, -4.460] |
| $\beta_{\text{size}}$                     |  *0.139* | [0.122, 0.156]   |
| $\beta_{\text{concept controlled}}$       | -0.055 | [-0.261, 0.141]  |
| $\beta_{\text{near synonymy controlled}}$ | -0.252 | [-0.578, 0.072]  |
| $\beta_{\text{Gosenshu--Shuishu}}$        |  0.020 | [-0.119, 0.158]  |
| $\beta_{\text{Shuishu--Goshuishu}}$       |  *0.158* | [0.019, 0.296]   |
| $\beta_{\text{Goshuishu--Kin'yoshu}}$     |  0.029 | [-0.114, 0.169]  |
| $\beta_{\text{Kin'yoshu--Shikashu}}$      |  *0.156* | [0.013, 0.297]   |
| $\beta_{\text{Shikashu--Senzaishu}}$      |  *0.212* | [0.073, 0.352]   |
| $\beta_{\text{Senzaishu--Shinkokinshu}}$  |  0.134 | [-0.006, 0.275]  |
| $\sigma$                                  |  0.702 | [0.692, 0.714]   |
| $\sigma_{\text{profile}}$                 |  0.358 | [0.310, 0.412]   |
| $\sigma_{\text{hu profile}}$              |  1.342 | [0.950, 1.907]   |
|                                           |        |                  |
| 観測数                                    |   8145 |                  |
| $R^2$                                     |  0.222 |                  |
| 周辺 $R^2$                                |  0.094 |                  |
* 考察<<sec:discussion>>
** 3水準における八代集の語彙変化の同調<<sec:disc-sync>>
統計モデリングの結果 ([[sec:stat-res]]) では，最大の変化を示す隣接2歌集は
見られなかったが，「古今→後撰」の語彙変化は小さく，「拾遺→後拾遺」「金
葉→詞花」「詞花→千載」の語彙変化は大きかった．このことは「後拾遺」を境
目とする初期の安定性と後期の変動性を支持した．ただし，いずれも転換点と
いえるほどの大きな変化ではなく，漸進的と見做すべきである．

クラスタ分析 ([[sec:clus-res]]) では，連続した勅撰集が1つのクラスタになり
やすい結果から勅撰集の変化の連続性が推測される．同概念水準とその他2水
準との比較では金葉と新古今のクラスタの扱いに違いがみられたことは，可視
化の結果 ([[sec:mds-res]]) の原理と関連していると考えられる．そのため，次
にまとめてとりあげる．

可視化の結果（[[sec:mds-res]]）では，三代集の「古今→後撰→拾遺」が比較的安
定していた一方，後拾遺以降は軸の正負が転換した．先行研究が示す「褻」か
ら「晴」への体裁変化 [cite/cf:@ueno1976Koshui] とは整合するが，同義類
義水準の語形選択にも転換が見られる点は注目に値する．同義類義水準での変
化は「褻→晴」として単純に解釈しがたく，さらなる検討が必要である．また，
金葉まで負軸から正軸への連続的推移があったが，金葉から詞花への転換は成
立年が近いにもかかわらず軸の正負が初めて反転した．これは金葉の撰者が同
時代の歌人を多く採録するのに対し，詞花が後拾遺の歌人の作を多く収録した
こと [cite/cf:@matsuda1939Shika] と関連し，詞花の後拾遺寄りへの回帰を
示唆すると考えられる．さらに，「金葉→詞花→千載→新古今」は正の値の範囲
内で揺れを示し，(1) 同時代重視から旧時代志向への回帰，(2) 再び同時代志向
への転換，(3) 最終的に新古今集における古歌を取り入れる本歌取り[fn:: 古
歌の一部を新たな歌に取り入れる技法．] の隆盛，といった新古の選好交替を
反映している可能性がある．

全体的には，本稿で設定した3水準の結果はいずれも近似しており，中間的水
準である同概念水準だけが異なる傾向を示した．文学史の記述とも整合するが，
本稿の分析手続き（語彙のサンプル調査）と文学史的事実が必ずしも対応して
いるわけではなく，偶然は排除できない．しかし，言語学的分析手法の計算文
学研究への応用可能性（主に数量的裏づけ）を示す予備的結果といえる．この
水準間の分析結果の同調については，次節で詳述する．

** 語彙分析における意味統制の水準<<sec:disc-ctrl>>
統計モデリングの結果 ([[sec:stat-res]]) によると，統制水準が異なっても大き
な変化はなかった．これは，八代集は「部立」などに規定されている共通のテー
マをもとに編纂され，テーマ差による変化が本来小さく，内容の統制を行って
も結果は変わりにくいためかもしれない．別資料での再検証が必要である．一
方，同概念水準でのみ変化量の有効なコントラクトが多くみられた理由として
は，次のように考えられる．同概念水準のサンプル語群は，部立など共通上位
概念内の語形で構成される場合が多く，テーマ内で語彙選択の変化を計算する
傾向がある．このようにテーマ別に絞ることで，全体では目立たない時代差が
顕著になりやすい．この論理では，同義類義水準の類語選択は八代集を通じて
安定的といえる．

中間の同概念統制水準の結果は他の2水準とやや異なったため，語群サンプリ
ング時の統制水準をルーズから厳格へ段階的に変えても，語彙変化が一方向に
連続的に見えやすく・見えにくくなることはなかった．このように意味内容面
の統制は，その影響が連続量的に振る舞わず，語彙変化の視座を離散的なもの
として切り替える操作に近いといえる．

** サンプル語群のサイズと変化量の関係<<sec:disc-size>>
[[sec:stat-res]] の統計モデリングでは，サイズが2〜5個のわずかな幅の中でも
サンプル語群のサイズ拡大に伴い変化量が大きくなる正の効果が確認された
（[[tbl:model-estimates]]）．プロファイル基盤分析の変化量はサイズに敏感で
あることがわかった．この結果は，マクロとミクロの語彙変化量の差が必ずし
も意味の統制によって生じるだけでなく，語群のサイズによっても生じる可能
性を示唆する．

** COMMENT 展望<<sec:disc-future>>
本稿の手法をめぐって展望を 3 点提案する．

*** 意味統制の水準調節の自動化<<sec:disc-auto>>
本稿では，意味統制の水準に分類番号を用いたが，分類番号のない古典語資料
も多い．分類番号に依存せず同様の手法を実現するには，語の階層的分類を自
動的に生成する手法が必要である．
 
*** 意味統制の水準の精緻化<<sec:disc-refine>>
[[sec:ext-sem-ctrl]] で述べた「統制なし → 意味分野統制 → 概念的同値語群統
制 → 形式的同値語群統制 → 同語異表記群統制 → 同義トークン異表記統制」
の5段階のうち，本稿では3段階に簡略化して採用したが，さらに精緻な水準設
定も考えられる．

また，先行研究で触れた多義性のある語形では，該当しないトークンを除外す
る処理が必要となる．たとえば /bank/ は「銀行」や「土手」を指し，別の同義
語群に割り当てることが望ましい．こうした同一語形の多義性の意味統制につ
いては[cite/c/t: @DePascale2021Scoring]が詳しい．さらに，計算上での変
化量の重みづけに語群内の整合性や語群の重要度を考慮する工夫
[cite/cf:@Ruette2014Semantic] も，語彙変化の把握をより精緻化しうる．

*** 意味以外の統制軸からみる語彙変化<<sec:disc-nonsem>>
本稿の検討は，意味の軸で語彙変化を段階的に把握する構想である．一方，語
彙研究では，意味以外の観点で語を部分語彙にまとめ，比較する手法が発達し
ている．たとえば「量的構造史モデル」[cite/cf:@ito2008Goi] は，使用度数
（高・中・低）と使用範囲（広・中・狭）で語彙を分類し，時代別の変化を検
証する．語彙史の研究では，ある視座で同一とみなす語を統合し，通時的変化
を整理することがによって「語彙的カテゴリー[cite/t/c:@abe2009Goia]」と
呼ばれている．語彙的カテゴリーは，日本語語彙史の研究領域（語の形態，語
種，位相，語形成など）を多面的に含む[cite/cf:@abe2009Goia]．これらの細
分領域で分類した部分語彙を比較すれば，意味の軸を超えた多様な語彙変化を
観測できる．本稿では意味軸のみを扱ったが，計算の型は他の軸でも応用可能
である．

* 結論<<sec:conclusion>>
本稿は，八代集の語彙変化を分析するために，語彙的変種計量論の分析手法
[cite/cf:@Speelman2003Profilebased] を基に，意味統制の水準を拡張し日本
語学の語彙論の観点を切り替える手法を八代集の語彙に適用した．具体的には，
無関係語群・同概念語群・類義同義語群の低・中・高の意味統制の3水準を設
け，八代集の各歌集でそれらのサンプル語群を収集し，語群内の語形分布の非
類似度を計算した．この変化量を用いた分析から，(1) 変化最大の隣接2歌集，
(2) 時代区分，(3) 推移揺れパターンを検討した．その結果，低・高の水準は類似
し，中間水準のみがやや異なった．プロファイルでの意味統制は視座の切り替
えに近く，語彙変化の各の側面を強調する役割を分担していると考える．なお，
文学史的事実とおおむね整合したことから，プロファイル基盤分析が文学研究
の裏づけに活用できよう．

#+begin_export latex
\begin{acknowledgment}
  本研究は，日本学術振興会外国人特別研究員制度（課題番号：25KF0133）よ
  り支援を受けました．
\end{acknowledgment}
#+end_export
#+print_bibliography:

